# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cgi/all/cgi.rbi
#
# cgi-0.5.1

module CGI::EscapeExt
  def escape(arg0); end
  def escapeHTML(arg0); end
  def escapeURIComponent(arg0); end
  def escape_uri_component(arg0); end
  def unescape(*arg0); end
  def unescapeHTML(arg0); end
  def unescapeURIComponent(*arg0); end
  def unescape_uri_component(*arg0); end
end
class CGI
  def _header_for_hash(options); end
  def _header_for_modruby(buf); end
  def _header_for_string(content_type); end
  def _no_crlf_check(str); end
  def accept_charset; end
  def env_table; end
  def header(options = nil); end
  def http_header(options = nil); end
  def initialize(options = nil, &block); end
  def nph?; end
  def out(options = nil); end
  def print(*options); end
  def self.accept_charset; end
  def self.accept_charset=(accept_charset); end
  def self.parse(query); end
  def stdinput; end
  def stdoutput; end
  extend CGI::Escape
  extend CGI::Util
  include CGI::Escape
  include CGI::Util
end
module CGI::Escape
  def escape(arg0); end
  def escapeElement(string, *elements); end
  def escapeHTML(arg0); end
  def escapeURIComponent(arg0); end
  def escape_element(string, *elements); end
  def escape_html(string); end
  def escape_uri_component(arg0); end
  def h(string); end
  def unescape(*arg0); end
  def unescapeElement(string, *elements); end
  def unescapeHTML(arg0); end
  def unescapeURIComponent(*arg0); end
  def unescape_element(string, *elements); end
  def unescape_html(string); end
  def unescape_uri_component(*arg0); end
end
module CGI::Util
  def pretty(string, shift = nil); end
  def rfc1123_date(time); end
end
module CGI::QueryExtension
  def [](key); end
  def accept; end
  def accept_charset; end
  def accept_encoding; end
  def accept_language; end
  def auth_type; end
  def cache_control; end
  def content_length; end
  def content_type; end
  def cookies; end
  def cookies=(arg0); end
  def create_body(is_large); end
  def files; end
  def from; end
  def gateway_interface; end
  def has_key?(*args); end
  def host; end
  def include?(*args); end
  def initialize_query; end
  def key?(*args); end
  def keys(*args); end
  def multipart?; end
  def negotiate; end
  def params; end
  def params=(hash); end
  def path_info; end
  def path_translated; end
  def pragma; end
  def query_string; end
  def raw_cookie2; end
  def raw_cookie; end
  def read_from_cmdline; end
  def read_multipart(boundary, content_length); end
  def referer; end
  def remote_addr; end
  def remote_host; end
  def remote_ident; end
  def remote_user; end
  def request_method; end
  def script_name; end
  def server_name; end
  def server_port; end
  def server_protocol; end
  def server_software; end
  def unescape_filename?; end
  def user_agent; end
end
class CGI::InvalidEncoding < Exception
end
class CGI::Cookie < Array
  def domain; end
  def domain=(str); end
  def expires; end
  def expires=(arg0); end
  def httponly; end
  def httponly=(val); end
  def initialize(name = nil, *value); end
  def inspect; end
  def name; end
  def name=(str); end
  def path; end
  def path=(str); end
  def secure; end
  def secure=(val); end
  def self.parse(raw_cookie); end
  def to_s; end
  def value; end
  def value=(val); end
end
