# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/simple_oauth/all/simple_oauth.rbi
#
# simple_oauth-0.4.1

module SimpleOAuth
end
module SimpleOAuth::Encoding
  def decode(value); end
  def encode(value); end
  def escape(value); end
  def unescape(value); end
end
class SimpleOAuth::ParseError < StandardError
end
class SimpleOAuth::InvalidOptionsError < StandardError
end
class SimpleOAuth::Parser
  def attributes; end
  def initialize(header); end
  def parse(valid_keys); end
  def scan_oauth_prefix; end
  def scan_params(valid_keys); end
  def scanner; end
  def store_if_valid(key, value, valid_keys); end
  def validate_comma_separator(key, comma); end
  def verify_complete; end
end
module SimpleOAuth::Signature
  def self.encode_base64(data); end
  def self.methods; end
  def self.normalize_name(name); end
  def self.register(name, rsa: nil, &block); end
  def self.register_builtin_methods; end
  def self.register_hmac_methods; end
  def self.register_plaintext_method; end
  def self.register_rsa_methods; end
  def self.registered?(name); end
  def self.reset!; end
  def self.rsa?(name); end
  def self.sign(name, secret, signature_base); end
  def self.unregister(name); end
end
class SimpleOAuth::Header
  def attributes; end
  def body; end
  def build_options(oauth, body); end
  def header_attributes; end
  def initialize(method, url, params, oauth = nil, body = nil); end
  def method; end
  def normalize_uri(url); end
  def normalized_attributes; end
  def normalized_params; end
  def options; end
  def params; end
  def secret; end
  def signature; end
  def signature_base; end
  def signature_params; end
  def signed_attributes; end
  def to_s; end
  def url; end
  def url_params; end
  def valid?(secrets = nil); end
  def validate_option_keys!; end
  extend SimpleOAuth::Encoding
  extend SimpleOAuth::Header::ClassMethods
end
module SimpleOAuth::Header::ClassMethods
  def body_hash(body, algorithm = nil); end
  def default_options(body = nil); end
  def encode_base64(data); end
  def generate_nonce; end
  def parse(header); end
  def parse_form_body(body); end
end
module SimpleOauth
end
