name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    if: github.actor == 'dependabot' || github.actor == 'andrewjkerr'
    runs-on: ubuntu-latest
    steps:
      - id: wait-for-sorbet
        name: Wait for Sorbet to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: master
          check-name: sorbet
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
      - id: automerge
        name: automerge
        uses: 'pascalgn/automerge-action@v0.15.5'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: 'dependencies'
          MERGE_METHOD: 'squash'
          MERGE_DELETE_BRANCH: true
